version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: carlosdonado/kubesample_backend
    env_file: .env
    labels:
      - traefik.enable=true
      - traefik.http.routers.app-http.rule=Host(`www.carlosdonado.com`)
      - traefik.http.routers.app-http.tls=true
      - traefik.http.routers.app-http.tls.certresolver=letsencrypt
      - traefik.http.services.my_custom_image.loadbalancer.server.port=80

  traefik:
    image: traefik:v2.3
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.toml:/etc/traefik/traefik.toml
      - traefik-public-certificates:/certificates

volumes:
  traefik-public-certificates:

